# Generated by Django 4.2.18 on 2025-01-27 04:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('monarch', models.CharField(default='Unknown', max_length=250)),
                ('formed', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=250)),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Government',
                'verbose_name_plural': 'Governments',
                'db_table': 'Government',
                'ordering': ('-formed',),
            },
        ),
        migrations.CreateModel(
            name='Empire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('emblem', models.ImageField(upload_to='Images/Empires/%Y/%m/%d/')),
                ('formed', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)])),
                ('monarch', models.CharField(max_length=250)),
                ('strength', models.CharField(choices=[('I', 'Irrelevant'), ('H', 'Feeble'), ('G', 'Weak'), ('F', 'Limited'), ('E', 'Influential'), ('D', 'Strong'), ('C', 'Ascendant'), ('B', 'Superpower'), ('A', 'Godly')], default='E', max_length=50)),
                ('reputation', models.CharField(choices=[('evil', 'Evil'), ('crooked', 'Crooked'), ('immoral', 'Immoral'), ('normal', 'Normal'), ('gentle', 'Gentle'), ('honorable', 'Honorable'), ('virtuous', 'Virtuous'), ('saintly', 'Saintly')], default='normal', max_length=20)),
                ('info', models.TextField()),
                ('platform', models.CharField(choices=[('A', 'Facebook'), ('B', 'Discord'), ('C', 'Reddit'), ('D', 'Whatsapp')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=40)),
                ('government', models.ForeignKey(default='self', on_delete=django.db.models.deletion.CASCADE, to='Factions.government')),
            ],
            options={
                'verbose_name': 'Empire',
                'verbose_name_plural': 'Empires',
                'db_table': 'Empires',
                'ordering': ('strength',),
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('emblem', models.ImageField(upload_to='Images/Clans/%Y/%m/%d/')),
                ('formed', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)])),
                ('monarch', models.CharField(max_length=250)),
                ('strength', models.CharField(choices=[('I', 'Irrelevant'), ('H', 'Feeble'), ('G', 'Weak'), ('F', 'Limited'), ('E', 'Influential'), ('D', 'Strong'), ('C', 'Ascendant'), ('B', 'Superpower'), ('A', 'Godly')], default='E', max_length=50)),
                ('reputation', models.CharField(choices=[('evil', 'Evil'), ('crooked', 'Crooked'), ('immoral', 'Immoral'), ('normal', 'Normal'), ('gentle', 'Gentle'), ('honorable', 'Honorable'), ('virtuous', 'Virtuous'), ('saintly', 'Saintly')], default='normal', max_length=20)),
                ('info', models.TextField()),
                ('platform', models.CharField(choices=[('A', 'Facebook'), ('B', 'Discord'), ('C', 'Reddit'), ('D', 'Whatsapp')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=40)),
                ('government', models.ForeignKey(default='self', on_delete=django.db.models.deletion.CASCADE, to='Factions.empire')),
            ],
            options={
                'verbose_name': 'Clan',
                'verbose_name_plural': 'Clans',
                'db_table': 'Clans',
                'ordering': ('strength',),
            },
        ),
    ]
