# Generated by Django 4.2.18 on 2025-01-27 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Factions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='government',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Factions.empire'),
        ),
        migrations.AlterField(
            model_name='empire',
            name='government',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Factions.government'),
        ),
    ]
