# Generated by Django 4.2.18 on 2025-01-28 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Factions', '0002_alter_clan_government_alter_empire_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='government',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
