# Generated by Django 4.2.18 on 2025-01-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factions', '0003_government_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='added'),
        ),
    ]
